/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

def fib(cnt:Int, end:Int, lst:List[Int]):List[Int] = {
    if (cnt < 2) fib(cnt+1, end, cnt+1::lst)
    else if (cnt >= end) lst
    else {
        val num = lst(0)+lst(1)
        fib(cnt+1, end, num::lst)
    }
}

val fibNums = fib(0,32,Nil).reverse
fibNums.foreach(n => print(n + " "))

println(fibNums.filter(n => n%2==0).sum)